// <auto-generated />
using Bulky.WebClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.WebClient.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712073955_AddedIndexInProductTable")]
    partial class AddedIndexInProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Models.Model.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<string>("Auther")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("Title", "Description", "ISBN")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            Auther = "Sudha Murty",
                            Description = "Here, There and Everywhere is a celebration of Sudha Murty's literary journey and is her 200th title across genres and languages. Bringing together her best-loved stories from various collections alongside some new ones and a thoughtful introduction, here is a book that is, in every sense, as multifaceted as its author.",
                            ISBN = "1234567890123",
                            ListPrice = 200.0,
                            Price = 174.0,
                            Price100 = 170.0,
                            Price50 = 160.0,
                            Title = "HereThere and Everywhere"
                        },
                        new
                        {
                            ProductId = 2L,
                            Auther = "The Dalai Lama",
                            Description = "In this unique and important book, one of the world's great spiritual leaders offers his practical wisdom and advice on how we can overcome everyday human problems and achieve lasting happiness.",
                            ISBN = "1234567890123",
                            ListPrice = 350.0,
                            Price = 320.0,
                            Price100 = 300.0,
                            Price50 = 310.0,
                            Title = "THE ART OF HAPPINESS"
                        },
                        new
                        {
                            ProductId = 3L,
                            Auther = "Peter Casey",
                            Description = "The first and only authorized biography on Tata Group including the Tata-Mistry legal battle, exclusive interviews with Ratan Tata, and never-before-seen photographs of the Tata family.",
                            ISBN = "1234567890123",
                            ListPrice = 500.0,
                            Price = 450.0,
                            Price100 = 430.0,
                            Price50 = 440.0,
                            Title = "The Story of Tata: 1868 to 2021"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
